forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('posts.urls')),
]

posts/urls.py
"""Urls patterns form posts app"""

from django.urls import path
from . import views


app_name = "posts"

urlpatterns = [
    path('', views.index, name='home'),  # home page
    path('posts', views.posts, name='posts'),  # posts page
    path('posts/<int:post_id>', views.post, name='post'),  # post page
    path('new_post/', views.new_post, name='new_post'), # add new post
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment' ), # add new comment
    path('edit_comment/<int:comment_id>', views.edit_comment, name='edit_comment'), # edit the comment
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'), # delete comment 
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'), # edit post
    path('delete_post/<int:post_id>', views.delete_post, name='delete_post'), # delete post
]

users/urls.py
"""Urls patterns form users app"""

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # include default django authentication urls
    path('', include('django.contrib.auth.urls')),  # home page
    path('confirm_logout', views.confirm_logout, name='confirm_logout'), # confirm loggeout
    path('register', views.register, name='register'), # user registration
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    """The model class for forum posts"""
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String representation of of Post"""
        return self.title


class Comment(models.Model):
    """The model class for comments posted on the posts"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String representation of of the comments"""
        return f"{self.text[:100]}"

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """This is form class for forum post"""
    class Meta:
        model = Post
        fields = ['title', 'body']
        labels = {'title': 'Title', 'body': 'Body'}
        widget = {'title': forms.TextInput(attrs={'placeholder': 'Post title'}), 'body': forms.Textarea(attrs={'col':80})}


class CommentForm(forms.ModelForm):
    """This is the form class for post comment"""
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Comment'}
        widget = {'text': forms.Textarea(attrs={'col': 80})}

posts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib import messages

from .models import Post, Comment
from .forms import PostForm, CommentForm


def index(request):
    """The view function to load the home page"""
    return render(request, 'posts/index.html')


def posts(request):
    """The view function to display forum posts"""
    forum_posts = Post.objects.order_by('-date_added')
    context = {'forum_posts': forum_posts}

    return render(request, 'posts/posts.html', context)


def post(request, post_id):
    """The view function for post details"""
    forum_post = Post.objects.get(id=post_id)
    post_comments = forum_post.comment_set.order_by('-date_added')
    context = {'forum_post': forum_post, 'post_comments': post_comments}

    return render(request, 'posts/post.html', context)


@login_required
def new_post(request):
    """The view function to add new post"""
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            # check if data is valid
            newpost = form.save(commit=False)
            newpost.owner = request.user
            newpost.save()
        messages.add_message(request, messages.SUCCESS, 'Post successfully added')
        return redirect('posts:posts')
    
    context = {'form': form}
    return render(request, 'posts/new_post.html', context)


@login_required
def new_comment(request, post_id):
    """The view function to add new comment"""
    post = Post.objects.get(id=post_id)

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            # check if the data passed validation 
            newcomment = form.save(commit=False)
            newcomment.post = post
            newcomment.owner = request.user
            newcomment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment successfully added')
            return redirect("posts:post", post_id=post_id)
    
    context = {'form': form, 'post': post}
    return render(request, 'posts/new_comment.html', context)


@login_required
def edit_comment(request, comment_id):
    """The view function to edit existing comment"""
    comment = Comment.objects.get(id=comment_id)

    if comment.owner != request.user:
        raise Http404

    post = comment.post

    if request.method != 'POST':
        form = CommentForm(instance=comment)
    else:
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Post successfully updated')
            return redirect('posts:post', post_id=post.id)

    context = {'form': form, 'post': post, 'comment': comment}
    return render(request, 'posts/edit_comment.html', context)


@login_required
def edit_post(request, post_id):
    """The view function to edit existing post"""
    post = Post.objects.get(id=post_id)

    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Post successfully updated')
            return redirect('posts:post', post_id=post_id)

    context = {'form': form, 'post': post}
    return render(request, 'posts/edit_post.html', context)


@login_required
def delete_post(request, post_id):
    """The view function to delete existing post"""
    posts = Post.objects.order_by('-date_added')
    post = Post.objects.get(id=post_id)

    if post.owner != request.user:
        raise Http404

    if post.delete():
        messages.add_message(request, messages.SUCCESS, 'You have successfully deleted your post')
    else:
        messages.add_message(request, messages.ERROR, 'There is a problem when trying to delete the post')

    context = {'forum_posts': posts}
    return render(request, 'posts/posts.html', context)
    

@login_required
def delete_comment(request, comment_id):
    """The view function to delete the post comment"""
    comment = Comment.objects.get(id=comment_id)
    forum_post = comment.post
    post_comments = forum_post.comment_set.order_by('-date_added')

    if comment.delete():
        messages.add_message(request, messages.SUCCESS, 'You have successfully deleted your comment') 
    else:
        messages.add_message(request, messages.ERROR, 'There is a problem when trying to delete the comment')


    context = {'forum_post': forum_post, 'post_comments': post_comments}
    return render(request, 'posts/post.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def confirm_logout(request):
    """This is the view function for confirming log out"""
    return render(request, 'registration/confirm_logout.html')


def register(request):
    """This is the view function for user resgistration"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user) # give the new user the session

            return redirect('posts:home')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

posts/templates/posts/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pro-Forum</title>
    {% bootstrap_css%}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href=" {% url 'posts:home' %} ">Pro-Forum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href=" {% url 'posts:posts' %} ">Posts<span class="sr-only">(current)</span></a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">

            
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">Hello, {{ user.get_full_name }}</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href=" {% url 'users:confirm_logout' %} ">Sign out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'users:login' %} ">Sign in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'users:register' %}">Sign up</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <div class="container px-5 pb-5">

        
        {% block page_header %}
            

        {% endblock page_header %}
            
        
        {% block content %}
            
        {% endblock content %}
            
      </div>
</body>
</html>

posts/templates/posts/edit_comment.html
{% extends "posts/base.html" %}

{% load bootstrap4 %}


{% block page_header %}
    <h1 class="display-1 text-muted">Edit Comment</h1>
{% endblock page_header %}
    
{% block content %}
    <h4 class="my-3"><a href="{% url 'posts:post' post.id %}">{{ post }}</a></h4>
    
    <form action="{% url 'posts:edit_comment' comment.id %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-dark" name="submit">Update comment</button>
        {% endbuttons %}
        
    </form>
{% endblock content %}

posts/templates/posts/edit_post.html
{% extends "posts/base.html" %}

{% load bootstrap4 %}


{% block page_header %}
    <h1 class="display-1 text-muted">Edit Post</h1>
{% endblock page_header %}
    

{% block content %}
    <h4>{{ post.title }}</h4>
    <p>{{ post.body }}</p>
    <form action="{% url 'posts:edit_post' post.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-dark">Update post</button>
        {% endbuttons %}
        
    </form>
{% endblock content %}
    

posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block content %}
    <div class="jumbotron my-5">
    <h1 class="display-1 class text-center text-muted">Professional Forum</h1>
        <p class="text-center">This is where professional from different fields meet and discuss ideas, innovations and challenges.</p>
    </div>
    
{% endblock content %}

posts/templates/posts/new_comment.html
{% extends "posts/base.html" %}

{% load bootstrap4 %}


{% block page_header %}
    <h1 class="display-1 text-muted my-2">Add Comment</h1>
{% endblock page_header %}
    

{% block content %}
    <h4 class="my-3"><a href="{% url 'posts:post' post.id %}">{{ post.title }}</a></h4>
    
    <form action="{% url 'posts:new_comment' post.id %}" method="post" clas="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-dark" name="submit">Add comment</button>
        {% endbuttons %}
        
    </form>
{% endblock content %}

posts/templates/posts/new_post.html
{% extends 'posts/base.html' %}

{% load bootstrap4 %}


{% block page_header %}
    <h1 class="display-1 my-2 text-muted">Add Post</h1>
{% endblock page_header %}
    

{% block content %}
    
    
    <form action="{% url 'posts:new_post'%}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-dark">Add post</button>
        {% endbuttons %}
        
    </form>
{% endblock content %}

posts/templates/posts/post.html
{% extends 'posts/base.html' %}


{% block page_header %}
    <h1 class="display-1 text-muted">Post</h1>
{% endblock page_header %}
    

{% block content %}
    
    <!-- Display messages when user has successfull delete the comments-->
    {% if messages %}
        {% for message in messages %}
      
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p class="alert alert-success">{{ message }}</p>
            {% else %}
                <p class="alert alert-error">{{ message }}</p>
            {% endif %}      
          
        {% endfor %}
    {% endif %}
        

    <h5 class="">{{ forum_post.title }} </h5>
    <p class="card-text text-muted mb-3">{{ forum_post.body }}</p>

    <h5 class="my-2">Comments
    {% if user.is_authenticated %}
        <small ><a class="mx-2 badge badge-light float-right" href="{% url 'posts:new_comment' forum_post.id %}">Add Comment</a></small>
    {% else %}
        <small class="mx-2 badge badge-light float-right">Login, to comment</small>
    {% endif %}
    </h5>
    
    

            {% for post_comment in post_comments %}
            <div class="card my-2">
                <div class="card-body">

                    <p class="card-text">{{ post_comment }}</p>
                    <small class="badge badge-light float-left">{{ post_comment.owner.get_full_name }}</small>
                    

                    {% if user.is_authenticated %}

                    {% if post_comment.owner == user  %}
                        <small><a class="badge badge-dark float-right mx-2" href="{% url 'posts:edit_comment' post_comment.id %}">Edit</a></small>
                        <small><a class="badge badge-danger float-right" href="{% url 'posts:delete_comment' post_comment.id %}">Delete</a></small>
                    {% endif %}
                        
                    {% endif %}

                    <small class="badge badge-light float-right mx-2">{{ post_comment.date_added }}</small>
                
                </div>
            </div>

            {% endfor %}
    
{% endblock content %} 

posts/templates/posts/posts.html
{% extends 'posts/base.html' %}


{% block page_header %}
    <h1 class="text-muted display-1">Posts</h1>
{% endblock page_header %}
    

{% block content %}

    <!--{% if message_success %}
        <p class="alert alert-success">{{ message_success }}</p>
    {% endif %}

    {% if message_error %}
        <p class="alert alert-error">{{ message_error }}</p>
    {% endif %}-->

    {% if messages %}
    
            {% for message in messages  %}
                
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <p class="alert alert-success">{{ message }}</p>
                {% else %}
                    <p class="alert alert-error">{{ message }}</p>
                {% endif %}
                
            {% endfor %}

    {% endif %}

    {% if user.is_authenticated %}
        <p><a href="{% url 'posts:new_post' %}" class="badge badge-dark">Add new post</a></p>
    {% endif %}

    {% for forum_post in forum_posts %}
        <div class="card border-secondary mb-3">
            <div class="card-body text-secondary">
                <h5 class="card-title"><a href="{% url 'posts:post' forum_post.id %}" > {{ forum_post.title }}</a></h5>
                    {% if user.is_authenticated %}
                        {% if forum_post.owner == user %}
                            <a class="float-right badge badge-dark mx-2" href="{% url 'posts:edit_post' forum_post.id %}">Edit</a> 
                            <a class="float-right badge badge-danger" href="{% url 'posts:delete_post' forum_post.id %}">Delete</a> 
                        {% endif %}
                    {% endif %} 
               
                <p class="card-text">{{ forum_post.body }}</p>
            </div>

            <div class="card-footer">
                <small class="badge badge-secondary">{{ forum_post.owner.get_full_name }}</small>&nbsp;&nbsp;
                
                
                
                {% if forum_post.comment_set.count > 0 %}
                    |&nbsp;&nbsp;<small><span class="badge badge-info">{{ forum_post.comment_set.count }}</span> Comments</small>
                {% endif %}
                    
                
                
                
                <small class="float-right"> {{ forum_post.date_added|date:'M d, Y H:i' }}</small>
            </div>
        </div>
    {% endfor %}

{% endblock content %}